public class GenerateSequence {
    //generates the following sequence of numbers:  a = ⟨0,1,1,2,3,5,8,...
    //is generated by the following formula: a0 =0; a1 =1 an =an−1 +an−2.
    public static int generate(int n) {
        if (n == 0) return 0;
        if (n == 1) return 1; //implement
        return 0;
    }
}
